export type ApplicationStatus = 
  | "DRAFT"
  | "SUBMITTED"
  | "PAYMENT_PENDING"
  | "PAYMENT_PROCESSING"
  | "PAYMENT_FAILED"
  | "PAYMENT_COMPLETED"
  | "APPOINTMENT_PENDING"
  | "APPOINTMENT_BOOKED"
  | "APPOINTMENT_COMPLETED"
  | "DOCUMENT_REVIEW"
  | "DOCUMENT_CORRECTION_REQUIRED"
  | "DOCUMENT_VERIFIED"
  | "OFFICER_REVIEW"
  | "POLICE_VERIFICATION_PENDING"
  | "POLICE_VERIFICATION_ASSIGNED"
  | "POLICE_VERIFICATION_IN_PROGRESS"
  | "POLICE_VERIFICATION_COMPLETED"
  | "POLICE_VERIFICATION_FAILED"
  | "CLARIFICATION_REQUIRED"
  | "FINAL_REVIEW"
  | "APPROVED"
  | "REJECTED"
  | "PASSPORT_PRINTING"
  | "PASSPORT_DISPATCHED"
  | "COMPLETED"
  | "CANCELLED"
  | "ON_HOLD"
  | "EXPIRED";

export const ALLOWED_TRANSITIONS: Record<ApplicationStatus, ApplicationStatus[]> = {
  DRAFT: ["SUBMITTED", "CANCELLED"],
  SUBMITTED: ["PAYMENT_PENDING", "PAYMENT_COMPLETED", "DOCUMENT_REVIEW", "CANCELLED"],
  PAYMENT_PENDING: ["PAYMENT_PROCESSING", "PAYMENT_COMPLETED", "PAYMENT_FAILED", "CANCELLED", "EXPIRED"],
  PAYMENT_PROCESSING: ["PAYMENT_COMPLETED", "PAYMENT_FAILED"],
  PAYMENT_FAILED: ["PAYMENT_PROCESSING", "PAYMENT_COMPLETED", "CANCELLED"],
  PAYMENT_COMPLETED: ["APPOINTMENT_PENDING", "APPOINTMENT_BOOKED", "DOCUMENT_REVIEW"],
  APPOINTMENT_PENDING: ["APPOINTMENT_BOOKED", "CANCELLED"],
  APPOINTMENT_BOOKED: ["APPOINTMENT_COMPLETED", "APPOINTMENT_PENDING", "DOCUMENT_VERIFIED", "CANCELLED", "EXPIRED"],
  APPOINTMENT_COMPLETED: ["DOCUMENT_REVIEW", "OFFICER_REVIEW", "POLICE_VERIFICATION_PENDING"],
  DOCUMENT_REVIEW: ["DOCUMENT_VERIFIED", "DOCUMENT_CORRECTION_REQUIRED", "REJECTED", "ON_HOLD"],
  DOCUMENT_CORRECTION_REQUIRED: ["DOCUMENT_REVIEW", "CANCELLED"],
  DOCUMENT_VERIFIED: ["POLICE_VERIFICATION_PENDING", "OFFICER_REVIEW", "APPOINTMENT_PENDING"],
  OFFICER_REVIEW: ["POLICE_VERIFICATION_PENDING", "FINAL_REVIEW", "DOCUMENT_CORRECTION_REQUIRED", "REJECTED", "ON_HOLD"],
  POLICE_VERIFICATION_PENDING: ["POLICE_VERIFICATION_ASSIGNED", "POLICE_VERIFICATION_COMPLETED", "APPROVED", "CANCELLED"],
  POLICE_VERIFICATION_ASSIGNED: ["POLICE_VERIFICATION_IN_PROGRESS", "POLICE_VERIFICATION_FAILED", "POLICE_VERIFICATION_COMPLETED", "CLARIFICATION_REQUIRED"],
  POLICE_VERIFICATION_IN_PROGRESS: ["POLICE_VERIFICATION_COMPLETED", "POLICE_VERIFICATION_FAILED", "CLARIFICATION_REQUIRED"],
  CLARIFICATION_REQUIRED: ["POLICE_VERIFICATION_IN_PROGRESS", "POLICE_VERIFICATION_ASSIGNED", "DOCUMENT_CORRECTION_REQUIRED", "REJECTED"],
  POLICE_VERIFICATION_COMPLETED: ["FINAL_REVIEW", "APPROVED"],
  POLICE_VERIFICATION_FAILED: ["FINAL_REVIEW", "REJECTED"],
  FINAL_REVIEW: ["APPROVED", "REJECTED", "ON_HOLD", "CLARIFICATION_REQUIRED"],
  APPROVED: ["PASSPORT_PRINTING"],
  PASSPORT_PRINTING: ["PASSPORT_DISPATCHED"],
  PASSPORT_DISPATCHED: ["COMPLETED"],
  ON_HOLD: ["DOCUMENT_REVIEW", "FINAL_REVIEW", "REJECTED", "CANCELLED"],
  REJECTED: ["CANCELLED"],
  CANCELLED: [],
  EXPIRED: [],
  COMPLETED: []
};

export function canTransition(currentStatus: string, nextStatus: string): boolean {
  const allowed = ALLOWED_TRANSITIONS[currentStatus as ApplicationStatus];
  if (!allowed) return false;
  return allowed.includes(nextStatus as ApplicationStatus);
}
